<?php
// Simple test file to verify PDF download works on mobile
// Test URL: test-pdf-mobile.php?test=1

if (isset($_GET['test'])) {
    // Include TCPDF library
    require_once 'vendor/autoload.php';
    
    // Create new PDF document
    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    
    // Set document information
    $pdf->SetCreator('KES Smart Attendance System');
    $pdf->SetAuthor('KES');
    $pdf->SetTitle('Mobile PDF Test');
    $pdf->SetSubject('Test Generated on ' . date('Y-m-d H:i:s'));
    
    // Set default header and footer fonts
    $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
    
    // Set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
    
    // Set margins
    $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
    
    // Set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
    
    // Set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
    
    // Add a page
    $pdf->AddPage();
    
    // Set font
    $pdf->SetFont('helvetica', '', 12);
    
    $html = '<h1 style="color: #007bff; text-align: center;">Mobile PDF Download Test</h1>';
    $html .= '<p style="text-align: center;">This is a test PDF file generated on: <strong>' . date('Y-m-d H:i:s') . '</strong></p>';
    $html .= '<div style="border: 1px solid #ddd; padding: 15px; margin: 20px 0; background-color: #f8f9fa;">';
    $html .= '<h2 style="color: #28a745;">Success!</h2>';
    $html .= '<p>If you are seeing this as a proper PDF file that downloaded automatically on your mobile device, the PDF download functionality is working correctly!</p>';
    $html .= '<ul>';
    $html .= '<li>✅ PDF Generation: Working</li>';
    $html .= '<li>✅ Mobile Download: Working</li>';
    $html .= '<li>✅ File Format: Valid PDF</li>';
    $html .= '</ul>';
    $html .= '</div>';
    $html .= '<p style="color: #6c757d; font-size: 10px; text-align: center;">Generated by KES Smart Attendance System using TCPDF</p>';
    
    // Print text using writeHTML
    $pdf->writeHTML($html, true, false, true, false, '');
    
    // Set headers for PDF download
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="mobile_test.pdf"');
    header('Cache-Control: no-cache, no-store, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');
    
    // Close and output PDF document
    $pdf->Output('mobile_test.pdf', 'D'); // 'D' for download
    exit;
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>PDF Mobile Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="mb-0">PDF Mobile Download Test</h5>
                    </div>
                    <div class="card-body">
                        <p>Click the button below to test PDF download on mobile devices:</p>
                        <button onclick="testPDFDownload()" class="btn btn-primary">
                            <i class="fas fa-download me-2"></i>Test PDF Download
                        </button>
                        <div id="feedback" class="mt-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function isMobileDevice() {
            return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
        }

        function testPDFDownload() {
            const feedback = document.getElementById('feedback');
            
            if (isMobileDevice()) {
                feedback.innerHTML = '<div class="alert alert-info"><i class="fas fa-mobile-alt me-2"></i>Mobile device detected. PDF should download automatically.</div>';
            } else {
                feedback.innerHTML = '<div class="alert alert-warning"><i class="fas fa-desktop me-2"></i>Desktop device detected. Testing mobile-style download...</div>';
            }
            
            // Use the same download method as reports.php
            window.location.href = 'test-pdf-mobile.php?test=1';
        }
    </script>
</body>
</html>